baseURL = "https://keerthanapg.com/"
title = "keerthanapg"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
disqusShortname = "keerthanapg"
pluralizelisttitles = false

[params]
author = "Keerthana Gopalakrishnan"
description = "Keerthana's personal website"
keywords = "blog,developer,personal"
info = "Building Embodied AGI"
avatarURL = "images/avatar.jpg"
#gravatar = "keerthanpg@gmail.com"
footerContent = "If you're so smart, why are you unhappy?"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
pluralizelisttitles = false
since = 2019
# Git Commit in Footer, uncomment the line below to enable it.
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = ["https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css"]
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# # If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
# serverURL = "analytics.example.com"

# # If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
# serverURL = "analytics.example.com"

# # If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# # If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# # If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# # Default value is "1", overwrite this if you are cloud-hosting
# siteID = "ABCDE"
# # For cloud-hosting, use provided URL, e.g. example.matomo.cloud
# serverURL = "analytics.example.com"

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
[params.googleTagManager]
id = "G-SR65R0C5W7"

# If you want to implement a Content-Security-Policy, add this section
# [params.csp]
# childsrc = ["'self'"]
# fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
# formaction = ["'self'"]
# framesrc = ["'self'"]
# imgsrc = ["'self'"]
# objectsrc = ["'none'"]
# stylesrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://fonts.googleapis.com/",
#   "https://cdn.jsdelivr.net/"
# ]
# scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
# prefetchsrc = ["'self'"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/keerthanpg/"

[[params.social]]
name = "Instagram"
icon = "fa fa-instagram"
weight = 2
url = "https://instagram.com/jomarch121/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/keerthanpg/"

[[params.social]]
icon = "ai ai-google-scholar"
title = "Google Scholar"
weight = 4
url = "https://scholar.google.com/citations?user=uemlfQYAAAAJ"

[languages.en]
languageName = "English"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Book"
weight = 3
url = "https://ai4robotics.org"

[[languages.en.menu.main]]
name = "Poetry"
weight = 5
url = "poetry/"

[[languages.en.menu.main]]
name = "Policy"
weight = 6
url = "policy/"

[[languages.en.menu.main]]
name = "Random"
weight = 7
url = "random/"

[[languages.en.menu.main]]
name = "Tech"
weight = 8
url = "tech/"

[[languages.en.menu.main]]
name = "Talks"
weight = 9
url = "talks/"

[[languages.en.menu.main]]
name = "Resume"
weight = 9
url = "https://drive.google.com/file/d/1U-n1jS46tL8dkm4s_AW6HAEVKMkQSwjW/view?usp=sharing"

#[[languages.en.menu.main]]
#name = "Book Reviews"
#weight = 10
#url = "bookreviews/"

[[languages.en.menu.main]]
name = "Photography"
weight = 11
url = "https://500px.com/p/keerthanpg?view=photos"